#!/usr/bin/env python3
"""Generate navigable indexes for Character Shape Research."""

from __future__ import annotations

import csv
import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ACCEPTED_LEDGER = ROOT / "research" / "SAMPLED_CHARACTERS.md"
REJECTED_LEDGER = ROOT / "research" / "REJECTED_CHARACTERS.md"
BATCH_DIR = ROOT / "research" / "batches"
GENERATED_DIR = ROOT / "research" / "generated"
MD_OUT = GENERATED_DIR / "SAMPLE_INDEX.md"
CSV_OUT = GENERATED_DIR / "SAMPLE_INDEX.csv"

START_MARKER = "<!-- ACCEPTED_APPEND_START -->"
END_MARKER = "<!-- ACCEPTED_APPEND_END -->"
HEADING_RE = re.compile(r"^##\s+(\d{3})\s+—\s+(.+?)\s*$", re.MULTILINE)
FIELD_RE_TEMPLATE = r"^-\s+{label}:\s*(.*?)\s*$"
SECTION_RE_TEMPLATE = r"^{}:\s*$"


@dataclass
class Entry:
    sample_id: int
    name: str
    status: str
    stored_in: str
    source_side: str = ""
    repo_path: str = ""
    structural_pattern: str = ""
    reusable_lesson: str = ""


def read_text(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def split_entries(text: str) -> list[tuple[int, str, str]]:
    matches = list(HEADING_RE.finditer(text))
    out: list[tuple[int, str, str]] = []
    for idx, match in enumerate(matches):
        start = match.start()
        end = matches[idx + 1].start() if idx + 1 < len(matches) else len(text)
        out.append((int(match.group(1)), match.group(2).strip(), text[start:end].strip()))
    return out


def extract_field(block: str, label: str) -> str:
    pattern = re.compile(FIELD_RE_TEMPLATE.format(label=re.escape(label)), re.MULTILINE)
    match = pattern.search(block)
    return match.group(1).strip() if match else ""


def extract_section_bullet(block: str, heading: str) -> str:
    # Finds first bullet after a section heading like "Structural pattern:".
    pattern = re.compile(rf"^{re.escape(heading)}:\s*\n-\s*(.+?)(?:\n|$)", re.MULTILINE)
    match = pattern.search(block)
    return match.group(1).strip() if match else ""


def extract_repo_path(block: str) -> str:
    match = re.search(r"Repo path:\s*\n-\s+`([^`]+)`", block, re.MULTILINE)
    return match.group(1).strip() if match else ""


def marked_block(text: str) -> str:
    if START_MARKER not in text or END_MARKER not in text:
        return ""
    start = text.index(START_MARKER) + len(START_MARKER)
    end = text.index(END_MARKER)
    if end <= start:
        return ""
    return text[start:end].strip()


def entry_from_block(sample_id: int, name: str, block: str, status: str, stored_in: str) -> Entry:
    return Entry(
        sample_id=sample_id,
        name=name,
        status=status,
        stored_in=stored_in,
        source_side=extract_field(block, "Source side"),
        repo_path=extract_repo_path(block),
        structural_pattern=extract_section_bullet(block, "Structural pattern"),
        reusable_lesson=extract_section_bullet(block, "Reusable lesson"),
    )


def collect_entries() -> list[Entry]:
    entries: dict[int, Entry] = {}

    accepted_text = read_text(ACCEPTED_LEDGER)
    for sid, name, block in split_entries(accepted_text):
        entries[sid] = entry_from_block(sid, name, block, "accepted", rel(ACCEPTED_LEDGER))

    rejected_text = read_text(REJECTED_LEDGER)
    for sid, name, block in split_entries(rejected_text):
        if sid in entries:
            continue
        entries[sid] = entry_from_block(sid, name, block, "rejected", rel(REJECTED_LEDGER))

    if BATCH_DIR.exists():
        for path in sorted(BATCH_DIR.glob("BATCH_*.md")):
            block = marked_block(read_text(path))
            if not block:
                continue
            for sid, name, entry_block in split_entries(block):
                if sid in entries:
                    continue
                entries[sid] = entry_from_block(sid, name, entry_block, "pending", rel(path))

    return [entries[sid] for sid in sorted(entries)]


def write_markdown(entries: list[Entry]) -> None:
    lines: list[str] = []
    lines.append("# Generated Sample Index")
    lines.append("")
    lines.append("This file is generated by `scripts/generate_research_index.py`. Do not edit by hand.")
    lines.append("")
    lines.append("| ID | Status | Name | Structural pattern | Stored in |")
    lines.append("|---:|---|---|---|---|")
    for e in entries:
        lines.append(f"| {e.sample_id:03d} | {e.status} | {e.name} | {e.structural_pattern} | `{e.stored_in}` |")
    lines.append("")
    write_text(MD_OUT, "\n".join(lines))


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def write_csv(entries: list[Entry]) -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    with CSV_OUT.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "sample_id",
                "name",
                "status",
                "source_side",
                "repo_path",
                "structural_pattern",
                "reusable_lesson",
                "stored_in",
            ],
        )
        writer.writeheader()
        for e in entries:
            writer.writerow(
                {
                    "sample_id": f"{e.sample_id:03d}",
                    "name": e.name,
                    "status": e.status,
                    "source_side": e.source_side,
                    "repo_path": e.repo_path,
                    "structural_pattern": e.structural_pattern,
                    "reusable_lesson": e.reusable_lesson,
                    "stored_in": e.stored_in,
                }
            )


def main() -> int:
    entries = collect_entries()
    write_markdown(entries)
    write_csv(entries)
    print(f"Generated {MD_OUT.relative_to(ROOT)}")
    print(f"Generated {CSV_OUT.relative_to(ROOT)}")
    print(f"Indexed entries: {len(entries)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
